# -*- coding: utf-8 -*-
"""Google News for python.py
© 2019 by theroyakash
Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Tu8DFRH3HaL1-4DMuCSK7yJ6Xv0X-Rte
"""

import lxml
import ssl
from bs4 import BeautifulSoup as soup
from urllib.request import urlopen


def news(xml_news_url):
    context = ssl._create_unverified_context()
    client = urlopen(xml_news_url, context=context)
    xml_page = client.read()
    client.close()
    
    soup_page = soup(xml_page, "xml")
    
    news_list = soup_page.findAll("item")
    
    for news in news_list:
        print(f'Title:   {news.title.text}')
        print(f'link:    {news.link.text}')
        print(f'Publication Date: {news.pubDate.text}')
        print("-"*20, "\n\n")


# you can add google news 'xml' URL here for any country/category
news_url = "https://news.google.com/rss?hl=en-IN&gl=IN&ceid=IN:en"
sports_url = "https://news.google.com/news/rss/headlines/section/topic/SPORTS.en_in/Sports?ned=in&hl=en-IN&gl=IN"

# now call news function with any of these url or BOTH
choice = int(input("Press 1 for Top News for today or\nPress 2 for Sports News for today"))
if choice == 1:
    news(news_url)
elif choice == 2:
    news(sports_url)
else:
    pass
